name: Generate blueprints

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Generate-files:
    runs-on: ubuntu-latest
    # container:
    #   image: dfdsdk/python-pipeline:0.0.4
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run script
        run: |
          # chmod +x ./aws-rds/blueprints/scripts/generate-blueprints.sh
          # ./aws-rds/blueprints/scripts/generate-blueprints.sh
          ./aws-rds/blueprints/scripts/aws-modules-rds/tools/scaffolding/generate_blueprints.sh
        shell: bash
