name: Generate blueprints

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  qa-env:
    runs-on: ubuntu-latest
    # container:
    #   image: dfdsdk/python-pipeline:0.0.4
    steps:
      - name: Run script
        working-directory: ./aws-rds/blueprints/scripts/
        run: ./generate-blueprints.sh
