name: Generate blueprints

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Generate-files:
    runs-on: ubuntu-latest
    # container:
    #   image: dfdsdk/python-pipeline:0.0.4
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run script
        working-directory: aws-rds/blueprints/scripts/aws-modules-rds/tools/scaffolding
        run: |
          ls -a
          ./generate_blueprints.sh
        shell: bash
