name: Test triggered workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  generate-blueprint:
    runs-on: ubuntu-latest

    steps:
      - name: Payload
        run: |
          echo ${{ github.event.client_payload.sha }}
          echo ${{ github.event.client_payload.release_tag }}
