name: Test triggered workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  generate-blueprint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout terraform-aws-rds
        uses: actions/checkout@v4
        with:
          repository: dfds/terraform-aws-rds
          path: ./modules
          ref: ${{ github.event.client_payload.release_tag }}
          token: ${{ secrets.AUTH_TOKEN }}
      - name: test
        run: |
          cd modules && ls
